services:
  - type: web
    name: saas-crm-fastapi-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: docker/api/Dockerfile
    healthCheckPath: /api/v1/health
    envVars:
      - key: ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: RUN_MIGRATIONS_ON_STARTUP
        value: "true"
      - key: CORS_ORIGINS
        value: "*"
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: ADMIN_PASSWORD
        value: "change-me-admin"
      - key: DATABASE_URL
        sync: false